### PR TITLE
Interactive Maps Preview Updates

### PR DESCRIPTION
**Pull request by StarMANK**
### **Updated Interactive Maps Preview** 
for Valley, Sandy Sunset, Salhan, District, Wakistan, Construction, Dusty Dew, Wine Paradise and Mutlu Islands

### CODE REVIEW

**Comment by alexcroox** [comment]
Thank you so much for this! Once we get it merged I'll process the map tiles. Some feedback/Qs

- Wakistan looks like we are replacing it with a tiny 728px image, we really need a 4k px image to tile

**Comment by StarMANK** [comment]
> 

il try to find one thats 4k px
 (the map got reworked)

**Comment by cadecuddy** [comment]
Map background color in `src/lib/map-config.ts` might have to change depending on how drastic of a change the edge colors went through in the updated pictures. I only saw the Multu example in Discord but it's prob worth looking into.

**Comment by alexcroox** [comment]
Yeah what I usually do is colour pick the dominent edge colour of the map

**Comment by alexcroox** [comment]
I've run the tiler on all these maps (except Wakistan as it's too blurry to use for zoomable map). Not had a chance to adjust the colours yet.

**Review by alexcroox — APPROVED** [review]

**Pull request merged**
